---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.10.24

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu/trusty64

suites:
  - name: default
    data_bags_path: "data_bags"
    encrypted_data_bag_secret_key_path: ".secrets/encrypted_data_bag_secret"
    run_list:
      - recipe[base::default]
      - recipe[webserver::default]
      - recipe[blog::default]
    attributes:
