source 'https://supermarket.chef.io'

metadata

#cookbook 'mysql',			'~>7.1'
cookbook 'webserver',		'0.0.1', path: '../webserver'
cookbook 'nginx-hardening',	'1.0.0', git: 'https://github.com/dev-sec/chef-nginx-hardening.git'
cookbook 'mysql2_chef_gem', '~> 1.0.1'
#cookbook 'build-essential'
#cookbook 'php-fpm', 		'~> 0.6.10'
cookbook 'tar', 			'>= 0.3.1'
cookbook 'database', '~> 5.1.2'