name 'blog'
maintainer 'dc'
maintainer_email 'dc@dustincamilleri.com'
license 'all_rights'
description 'Installs/Configures blog'
long_description 'Installs/Configures blog'
version '0.0.1'

#depends 'mysql', '~>7.1'
depends 'webserver', '0.0.1'
depends 'mysql2_chef_gem', '~> 1.0.1'
#depends 'build-essential'
#depends 'php-fpm', '~> 0.6.10'
depends 'tar', '>= 0.3.1'
depends 'database', '~> 5.1.2'
#depends 'wordpress', '~>3.0.0'