name 'blog'
maintainer 'dc'
maintainer_email 'dc@dustincamilleri.com'
license 'all_rights'
description 'Installs/Configures blog'
long_description 'Installs/Configures blog'
version '0.0.1'

depends 'webserver', '0.0.1'
depends 'mysql2_chef_gem', '~> 1.0.1'
depends 'tar', '>= 0.3.1'
depends 'database', '~> 5.1.2'